INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('B22662146', 'Lunel', 'Cases', 'Murphy', 3);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('R14328249', 'Boulogne-sur-Mer', 'Alvarados', 'Christen', 2);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('G42185815', 'Orléans', 'Kochs', 'Barry', 4);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('R32281327', 'Cambrai', 'Dudleys', 'Wylie', 5);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('O75041198', 'La Rochelle', 'Slaters', 'Colleen', 1);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('V73654623', 'Vandoeuvre-lès-Nancy', 'Monroes', 'Linus', 2);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('Z17235374', 'Le Puy-en-Velay', 'Fischers', 'Isabella', 4);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('R84623671', 'Auxerre', 'Mccartys', 'Claudia', 3);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('D78106598', 'Orléans', 'Castanedas', 'Beau', 5);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('S85694088', 'Le Puy-en-Velay', 'Dorseys', 'Colby', 2);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('Y68664772', 'Orléans', 'Cotes', 'Juliet', 4);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('Q66676064', 'Saint-Lô', 'Mcphersons', 'Perry', 3);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('B10648624', 'Beauvais', 'Haneys', 'Nolan', 5);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('N26332417', 'Montpellier', 'Meyerss', 'Mufutau', 1);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('F42358144', 'Lille', 'Aguirres', 'Halee', 2);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('I57332640', 'La Rochelle', 'Emersons', 'Jenette', 4);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('B51423637', 'Ajaccio', 'Cruzs', 'Hayden', 3);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('C45328794', 'Sarreguemines', 'Lawrences', 'Brittany', 5);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('H48344613', 'Chalon-sur-Saône', 'Irwins', 'Alisa', 2);
INSERT INTO Enseignant (Id_enseignant, Adresse, Nom_prof, Prenom_prof, Nombre_max_stagiaire) VALUES ('R41814241', 'Fréjus', 'Miless', 'Aidan', 4);
