INSERT INTO Addr_name (Address) VALUES ('Lunel');
INSERT INTO Addr_name (Address) VALUES ('Boulogne-sur-Mer');
INSERT INTO Addr_name (Address) VALUES ('Brive-la-Gaillarde');
INSERT INTO Addr_name (Address) VALUES ('Orléans');
INSERT INTO Addr_name (Address) VALUES ('Cambrai');
INSERT INTO Addr_name (Address) VALUES ('La Rochelle');
INSERT INTO Addr_name (Address) VALUES ('Vandoeuvre-lès-Nancy');
INSERT INTO Addr_name (Address) VALUES ('Auxerre');
INSERT INTO Addr_name (Address) VALUES ('Le Puy-en-Velay');
INSERT INTO Addr_name (Address) VALUES ('Saint-Lô');
INSERT INTO Addr_name (Address) VALUES ('Beauvais');
INSERT INTO Addr_name (Address) VALUES ('Montpellier');
INSERT INTO Addr_name (Address) VALUES ('Lille');
INSERT INTO Addr_name (Address) VALUES ('Ajaccio');
INSERT INTO Addr_name (Address) VALUES ('Sarreguemines');
INSERT INTO Addr_name (Address) VALUES ('Chalon-sur-Saône');
INSERT INTO Addr_name (Address) VALUES ('Fréjus');
INSERT INTO Addr_name (Address) VALUES ('413 Av. Gaston Berger, 13100 Aix-en-Provence');
INSERT INTO Addr_name (Address) VALUES ('Albi');
INSERT INTO Addr_name (Address) VALUES ('Saint-Étienne-du-Rouvray');
INSERT INTO Addr_name (Address) VALUES ('Agen');
INSERT INTO Addr_name (Address) VALUES ('Perpignan');
INSERT INTO Addr_name (Address) VALUES ('Dreux');
INSERT INTO Addr_name (Address) VALUES ('Évreux');
INSERT INTO Addr_name (Address) VALUES ('Angoulême');
INSERT INTO Addr_name (Address) VALUES ('Paris');
INSERT INTO Addr_name (Address) VALUES ('Aulnay-sous-Bois');
INSERT INTO Addr_name (Address) VALUES ('Périgueux');
INSERT INTO Addr_name (Address) VALUES ('Villenave-d_Ornon');
INSERT INTO Addr_name (Address) VALUES ('Dijon');
INSERT INTO Addr_name (Address) VALUES ('Marcq-en-Baroeul');
INSERT INTO Addr_name (Address) VALUES ('Colmar');