INSERT INTO Study_at (Student_number, Department_name) VALUES ('B82656814', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('Y26472238', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('B14955698', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S47843997', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('D83154177', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('D97153746', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('O18468102', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('Y51150412', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('U84466434', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('P43090772', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('H47232920', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('C35008429', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('U64274615', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('C67683232', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('K71754824', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S60552402', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('R15640225', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('Q49315273', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('Q44691862', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('R27448536', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('F03019685', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('B13433362', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('C70741722', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('Z21392555', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('D06749632', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S33551879', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('W36736211', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('R56931231', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('C25155368', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('N65851779', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('B61337468', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('X13183474', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('V88128782', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('T37746743', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('B62553911', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('L86338389', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('I69456267', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('B40239339', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('H14863692', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('T74730069', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('P15063542', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('M33382558', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('U60431135', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('M34783033', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('O64863218', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('V51296562', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('X62847517', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('J95442213', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('J17865151', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('E35962258', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('D93211952', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('K11370670', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('L61872638', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('L10783379', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('K14815933', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('L24677322', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('C90023858', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('I40581417', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('U44158779', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('U18373223', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('Q61178516', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('X76731856', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('T97220228', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('G12824677', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('V62147234', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('G23254613', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('Q78353565', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('C86247631', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('L27312376', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('P36571511', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('P08567312', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('N63215569', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('F97127967', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('M87422896', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('E61327716', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('E89368273', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('B66537879', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('R47255376', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('N38268628', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('O14132859', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('J93570177', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('M04459427', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('I07746111', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('P08664347', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('X77543350', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('L65151712', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('C69818318', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('O53891790', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('P81524434', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('V36767537', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('X75842440', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('I89553120', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('T73738333', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('M82251745', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('R18634641', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('P48118413', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('U36743854', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('D75827545', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('D21640336', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('M05227831', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('V77414394', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('Y67152665', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('E67351791', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('E27192381', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('F55522863', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('F48626191', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('T91338854', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('L64795769', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('M22758723', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('P04312112', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('H22564973', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('H51561432', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('E73591777', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('X87316377', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('I47154666', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('N74214375', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('Y75773561', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('N97352362', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('O25165661', 'IUT_INFO_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('J81275836', 'IUT_INFO_AIX');

-- insert de relation pour des etudiant en TC
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S12345678', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S22345679', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S32345680', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S42345681', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S52345682', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S62345683', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S72345684', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S82345685', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S92345686', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S03345687', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S13345688', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S23345689', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S33345690', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S43345691', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S53345692', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S63345693', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S73345694', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S83345695', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S93345696', 'IUT_TC_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S03345697', 'IUT_TC_AIX');

-- insert de relation pour des etudiant en GMP
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S14345678', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S24345679', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S34345680', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S44345681', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S54345682', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S64345683', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S74345684', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S84345685', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S94345686', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S05345687', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S15345688', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S25345689', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S35345690', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S45345691', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S55345692', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S65345693', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S75345694', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S85345695', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S95345696', 'IUT_GEA_AIX');
INSERT INTO Study_at (Student_number, Department_name) VALUES ('S06345697', 'IUT_GEA_AIX');

-- Ajout des étudiants dans Study_at avec un département NULL
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('B22662146', 'Lunel', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('R14328249', 'Boulogne-sur-Mer', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('G42185815', 'Orléans', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('R32281327', 'Cambrai', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('O75041198', 'La Rochelle', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('V73654623', 'Vandoeuvre-lès-Nancy', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('Z17235374', 'Le Puy-en-Velay', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('R84623671', 'Auxerre', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('D78106598', 'Orléans', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('S85694088', 'Le Puy-en-Velay', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('Y68664772', 'Orléans', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('Q66676064', 'Saint-Lô', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('B10648624', 'Beauvais', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('N26332417', 'Montpellier', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('F42358144', 'Lille', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('I57332640', 'La Rochelle', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('B51423637', 'Ajaccio', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('C45328794', 'Sarreguemines', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('H48344613', 'Chalon-sur-Saône', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('R41814241', 'Fréjus', 'Domicile_1');
