INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('B22662146', 'Lunel', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('R14328249', 'Boulogne-sur-Mer', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('G42185815', 'Orléans', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('R32281327', 'Cambrai', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('O75041198', 'La Rochelle', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('V73654623', 'Vandoeuvre-lès-Nancy', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('Z17235374', 'Le Puy-en-Velay', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('R84623671', 'Auxerre', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('D78106598', 'Orléans', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('S85694088', 'Le Puy-en-Velay', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('Y68664772', 'Orléans', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('Q66676064', 'Saint-Lô', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('B10648624', 'Beauvais', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('N26332417', 'Montpellier', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('F42358144', 'Lille', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('I57332640', 'La Rochelle', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('B51423637', 'Ajaccio', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('C45328794', 'Sarreguemines', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('H48344613', 'Chalon-sur-Saône', 'Domicile_1');
INSERT INTO Has_address (Id_teacher, Address, Type) VALUES ('R41814241', 'Fréjus', 'Domicile_1');